// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PomodoroTimeTracker.Infrastructure.Data;

#nullable disable

namespace PomodoroTimeTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251201130732_AddSoundSelectionSettings")]
    partial class AddSoundSelectionSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PomodoroTimeTracker.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PomodoroTimeTracker.Domain.Entities.PomodoroSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Objective")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StartTime");

                    b.ToTable("PomodoroSessions");
                });

            modelBuilder.Entity("PomodoroTimeTracker.Domain.Entities.PomodoroSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlarmSound")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AlarmVolume")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FlashWindow")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("LongBreakDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongBreakInterval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PlaySound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShortBreakDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowNotification")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseAlarm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WrapUpNotificationSound")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WrapUpNotificationVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WrapUpPeriodMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PomodoroSettings");
                });

            modelBuilder.Entity("PomodoroTimeTracker.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Name", "ClientId")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PomodoroTimeTracker.Domain.Entities.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StartTime");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("PomodoroTimeTracker.Domain.Entities.PomodoroSession", b =>
                {
                    b.HasOne("PomodoroTimeTracker.Domain.Entities.Project", "Project")
                        .WithMany("PomodoroSessions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PomodoroTimeTracker.Domain.Entities.Project", b =>
                {
                    b.HasOne("PomodoroTimeTracker.Domain.Entities.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("PomodoroTimeTracker.Domain.Entities.TimeEntry", b =>
                {
                    b.HasOne("PomodoroTimeTracker.Domain.Entities.Project", "Project")
                        .WithMany("TimeEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PomodoroTimeTracker.Domain.Entities.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("PomodoroTimeTracker.Domain.Entities.Project", b =>
                {
                    b.Navigation("PomodoroSessions");

                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
