<?xml version="1.0" encoding="UTF-8" ?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
        <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
        <Platforms>x86;x64;ARM64</Platforms>

        <!-- WinUI 3 -->
        <UseWinUI>true</UseWinUI>

        <!-- Project Options -->
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>PomodoroTimeTracker.ViewModels</RootNamespace>

        <!-- App Options -->
        <UseRidGraph>true</UseRidGraph>
        <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) >= 8">win-x86;win-x64;win-arm64</RuntimeIdentifiers>
        <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &lt; 8">win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.*" />
        <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.*" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PomodoroTimeTracker.Application\PomodoroTimeTracker.Application.csproj" />
        <ProjectReference Include="..\PomodoroTimeTracker.Domain\PomodoroTimeTracker.Domain.csproj" />
    </ItemGroup>
</Project>
